name: Elixir CI

on:
  push:
    paths:
      - "elixir"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      matrix:
        otp: ['28.0']       
        elixir: ['1.19.3']    
    steps:
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clean to rule out incremental build as a source of flakiness
      working-directory: elixir/adventofcode
      if: github.run_attempt != '1'
      run: |
        mix deps.clean --all
        mix clean
      shell: sh
      
    - name: Install dependencies
      working-directory: elixir/adventofcode
      run: mix deps.get

    - name: Compiles without warnings
      working-directory: elixir/adventofcode
      run: mix compile --warnings-as-errors

    - name: Check Formatting
      working-directory: elixir/adventofcode
      run: mix format --check-formatted

    - name: Run tests
      working-directory: elixir/adventofcode
      run: mix test
